apiVersion: v1
kind: Service
metadata:
  name: stem-separation
spec:
  selector:
    app: stem-separation
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stem-separation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stem-separation
  template:
    metadata:
      labels:
        app: stem-separation
    spec:
      containers:
        - name: stem-separation
          image: stem-separation:1
          imagePullPolicy: Never
          env:
            - name: PORT
              value: '4000'
            - name: DB_URL
              value: postgresql://postgres:postgres@postgres-db:5432/postgres
            - name: RABBIT
              value: amqp://test:test@rabbit:5672
